### ISSUE TITLE
truststore_password should be :validate => :password

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-mixin-http_client#2]
Doing :validate => :password will wrap the value in an object which resists leaking the password secret by obscuring #to_s and #inspect calls.

Changes:
* Set this to :validate => :password 
* Change @truststore_password uses to be `@truststore_password.value` to get the actual configured value.

**Comment by andrewvc** [comment]
@jordansissel can you review https://github.com/logstash-plugins/logstash-mixin-http_client/issues/2 ? This fixes this and some other issues.

**Comment by andrewvc** [comment]
Resolved with #3
